-- CAUTION: RUNNING THIS FILE WILL DELETE ALL DATA IN THE DATABASE
-- RUN THIS FILE ONLY IF YOU ARE CERTAIN THAT SENSITIVE DATA WILL NOT BE LOST

PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS SecurityQuestion;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserMessage;
DROP TABLE IF EXISTS JobCategory;
DROP TABLE IF EXISTS BadgeContent;
DROP TABLE IF EXISTS SkillCategory;
DROP TABLE IF EXISTS SkillCategoryByUser;
DROP TABLE IF EXISTS PaymentType;
DROP TABLE IF EXISTS JobPayment;
DROP TABLE IF EXISTS JobCategoryByUser;
DROP TABLE IF EXISTS LeaderboardContent;
DROP TABLE IF EXISTS UserBadge;
DROP TABLE IF EXISTS CertificationContent;
DROP TABLE IF EXISTS JobContent;
DROP TABLE IF EXISTS SkillCategoriesByJob;
DROP TABLE IF EXISTS JobReview;
DROP TABLE IF EXISTS ReviewContent;
DROP TABLE IF EXISTS OrganizationMember;
DROP TABLE IF EXISTS EmployerJob;
DROP TABLE IF EXISTS JobCategoriesByJob;
DROP TABLE IF EXISTS MessageContent;
DROP TABLE IF EXISTS AchievementMetric;
DROP TABLE IF EXISTS AchievementContent;
DROP TABLE IF EXISTS UserAchievement;
DROP TABLE IF EXISTS UserSpecies;
DROP TABLE IF EXISTS PetOwner;
DROP TABLE IF EXISTS EmployeeJob;
DROP TABLE IF EXISTS UserSecurityAnswer;
DROP TABLE IF EXISTS UserCertification;
DROP TABLE IF EXISTS UserReview;
DROP TABLE IF EXISTS PaymentContent;

PRAGMA foreign_keys = ON;